### ISSUE TITLE
Can't load prototype without getting a warning

### ISSUE THREAD

**Issue by caseyhoward** [mynyml/harmony#7]
I don't know if anybody else has ran into this, but I can't load prototype without getting the following:

```
not implmented yet: XPath function local-name()
xpath failure: TypeError: v1 is undefined
WARNIING:   [Thu Apr 15 2010 17:16:42 GMT-0700 (PST)] {ENVJS} could not load script  http://ajax.googleapis.com/ajax/libs/prototype/1.6.1/prototype.js: v1 is undefined
```

Here's a way to reproduce: 

```
Harmony::Page.new(<<-HTML)
  <html>
    <head>
      <script src="http://ajax.googleapis.com/ajax/libs/prototype/1.6.1/prototype.js" type="text/javascript"></script>
    </head>
    <body>
    </body>
  </html>
HTML
```

I don't see any options for disabling this output. Is there a workaround that doesn't involve redirecting stderr?

**Comment by mynyml** [comment]
The issue has been reported previously: http://github.com/mynyml/harmony/issues/closed#issue/4

iirc `local-name()` is simply not implemented in envjs, but it's only used in the specific version of prototype that you're using. If possible, the simplest solution would be to change the prototype version. Otherwise you could try reporting the issue upstream on envjs.

**Comment by caseyhoward** [comment]
Ok, thanks.

**Comment by mcmire** [comment]
If anyone else runs into this, using Prototype 1.7 (RC at the time of this writing) seems to work (since it uses Sizzle as the selector engine instead of Prototype's built-in one).
